### ISSUE TITLE
Reproject not working for 2-band grayscale input

### ISSUE THREAD

**Issue by grabermtw** [lucianpls/mod_reproject#15]
Inputs with 2 bands (grayscale + alpha) are not being reprojected successfully.

The following request to GIBS-in-the-Cloud returns the following image for EPSG:4326:
https://gitc.earthdata.nasa.gov/wmts/epsg4326/best/GOES-East_ABI_Band2_Red_Visible_1km/default/1km/0/0/0.png
![GOES-East_ABI_Band2_Red_Visible_1km_EPSG4326](https://github.com/lucianpls/mod_retile/assets/36314617/438297f1-589f-4943-9e4b-06375aad90f0)

When that layer is reprojected to EPSG:3857 using mod_retile, the following erroneous image is produced:
https://gitc.earthdata.nasa.gov/wmts/epsg3857/best/GOES-East_ABI_Band2_Red_Visible_1km/default/GoogleMapsCompatible_Level7/0/0/0.png
![GOES-East_ABI_Band2_Red_Visible_1km_EPSG3857](https://github.com/lucianpls/mod_retile/assets/36314617/8ab753ca-2430-4788-90c5-9e61c783a44a)

Appreciate the help!

**Comment by lucianpls** [comment]
@grabermtw 
At a quick glance, it should work. Make sure the input and output AHTSE configuration files show 2 bands.
The files in the ReTile_ConfigurationFiles directive.

**Comment by lucianpls** [comment]
@grabermtw
It works for me, when the size and tilesize list 2 bands.
I got this, which is scaled and re-tiled to 256x256
![0](https://github.com/lucianpls/mod_retile/assets/6413756/49dd0579-b854-42e9-9959-202fb6c55bd4)

**Comment by grabermtw** [comment]
Thanks @lucianpls! Got it to work after checking those files, it seems it was as simple as the number of bands being specified incorrectly. Appreciate the help!
